### ISSUE TITLE
DaDaDee - Ruby Developer - Saigon - FT

### ISSUE THREAD

**Issue by huynhquancam** [awesome-jobs/jobs#135]
![dadadee-logo](https://cloud.githubusercontent.com/assets/5930347/11800206/f626f128-a30c-11e5-9448-57cf7439060b.png)

Founded in 2015 and based in Singapore, [Dadadee](https://dadadee.com) is a trusted community marketplace for people to list, buy or sell goods and services online in bulk. By tapping on crowd-buying and reverse-auction, buyers enjoy low prices due to economies of scale and suppliers get to sell their products and services in bulk.

We are also a partner of [Fedena](http://www.fedena.com), a all-in-one school management software & student information system used by educational institutions worldwide for administration & management related activities, trusted by 40,000+ schools and over 20 millions students and teachers.

Presently we are looking for one Ruby developer to join our team in Saigon. If you have a passion for e-commerce, reverse-auction and crowd-buying, and do love the beauty of Ruby language brings, then Dadadee might be the next stop of your career.

## Location

* District 10, Saigon, Vietnam.

## Our tech stack

- Ruby / Ruby on Rails / Grape.
- Linux / Docker / Ansible / Jenkins.

## Requirements

* 1+ years of commercial experience in Ruby.
* Good English verbal and written communication skills.
* Good logical thinking.
* Believe in TDD.
* Experience in development operations e.g Jenkins, Docker, Ansible is a big plus.
* Having OSS contribution is a big plus.

## You'll be responsible for two things.

* Build features or anything cool and useful.
* More importantly, ensure your features not to spoil the soup of 30,000+ users.

## What we offer

* Young, friendly team member with open, flexible product environment.
* Great opportunity for career development.
* 13th month of salary.
* Performance evaluation twice a year for salary increment and bonus.
* Attractive renumeration packages that matches your experience and skills.

### Contact

Interested in the job? Drop me an email at jack.huang@dadadee.com (with your Github, Bitbucket URLs)

**Comment by huynhquancam** [comment]
up up `#yolo`

**Comment by joneslee85** [comment]
up up up cho nó lên

**Comment by huynhquancam** [comment]
lâu lâu em nó mạn phép xin được up một phát.

**Comment by joneslee85** [comment]
chú không phải xoắn, up hộ cái
