### ISSUE TITLE
AsianTech - Ruby on Rails Developer / Internship - Da Nang - FT

### ISSUE THREAD

**Issue by vinhnglx** [awesome-jobs/jobs#152]
## Company

We at Asian Tech want to be at the forefront of the IT revolution in Vietnam. Our engineers work not only for professional and technological development but also aspire to be part of an internationally expanding economy that is shaping the future of their country. 

## Location

* Da Nang, Vietnam

## Salary Expectation

* Negotiable

## Requirements

* At least, 1-year experience as a Web developer.
* Experienced working with Ruby/Rails (level Beginner / Intermediate / Advanced).
* Able to code review. 
* Strong knowledge and experience with HTML, CSS, JavaScript, SQL.
* Familiar working with Linux.
* Solid knowledge and experience about OOP and MVC model.
* Good knowledge or experienced with Cache, LESS/SASS/SCSS, frontend-frameworks (Angularjs, Reactjs, Polymerjs, …), AWS Services.
* Experienced working with git (Github, Gitlab, Bitbucket, …)
* Good teamwork and communication skill.
* Good time management and problem-solving skill.
* Able to coach and mentor junior members.
* Good learning attitude, professionalism and high sense of responsibility. 
* Good command of English is a must; Japanese speaking is a big plus.

### You’ll be responsible for

* Analyze system requirement and review specifications.
* Develop OOP code base for Web application using Ruby on Rails framework.
* Design system component and determine production environments.
* Participate in creating solutions for the high-level requirement.
* Work closely with project manager and UX designer. 
* Ensure Unit testing is done for all developed code.
* Participate in code review and optimization to maximize system performance.
* Report to Ruby team manager, and proactively contribute to skills building activities for members in the team.

### Benefits

- Performance review and salary adjustment 2 times a year
- Promotion opportunity
- Monthly team-building fund
- English/Japanese certificate incentive bonus program
- Annual company trip.
- International clients and the multi-cultural working environment.

### Fun fact

- With over 60 members combined, our iOS + Android teams are the biggest in Da Nang and central Vietnam
- We currently have 8 Japanese members.
- Our staff ratio is 75% men, 25% women.
- With 115 intermediate English speakers, English communication is highly valued
25 speakers of Japanese (N3 or higher), many of whom have lived and worked in Japan

### Contact

Apply by submitting an email to recruitment@asiantech.vn (with your GitHub, Bitbucket URL...)

**Comment by joneslee85** [comment]
:+1:

**Comment by vinhnglx** [comment]
up
