### ISSUE TITLE
Livepass Viet Nam - Ruby Developer (leader and Senior) - Da Nang - FT

### ISSUE THREAD

**Issue by hoanglongle** [awesome-jobs/jobs#153]
## Company
Livepass Viet Nam Co.,ltd
Lot FG, 12th Floor, Danang Software Park, 02 Quang Trung, Hai Chau, Da Nang
Tên người liên hệ: Mr. Long
Qui mô công ty: 25-99
Livepass Viet Nam co.,ltd
“Live” + “Pass”
Livepass means “make living and pass to tech for human life”.
Livepass is Japanese company.
Livepass VN is branch in Viet Nam.
We are Apps and web development company.
We are young and fast-growing.
Our office in Software park at Da Nang. 
Website: http://www.livepass.jp/

## Location
Da Nang, Viet Nam
Onsite Japan.
## Salary Expectation
Negotiable
## Requirements
- Minimum over 1.5 years experience coding in Ruby;
- Experience about Scrum and Sprint ;
- Experience solving coding problems;
- passion and desire to learn and grow Ruby skill;
- knowledge in UI (HTML, CSS), Jquery/Javascript, coffeescript, sass, html;
- knowledge of database systems;
- Knowledgeable and good use Git, bitbucket;
- Intermediate or higher English ;
- know Japanese is an advantage.

## Skills
- Good Problem Assessment/Problem Solving skills.
- Ability of learning new technical skill.
- Ability of team working.
- Having the ability to work autonomously and teamwork abilities.
- To actively learn new techniques and have the ability to acquire a flexibly.
- Ability to handle pressure and meet strict deadlines.
- Venture Spirit.
- Have good health and physical fitness.

## Benefits:
- Fulltime position;
- You Have the opportunity to work onsite in Japan (3 - 6 months).
- Salary Assessment by ability;
- Fast internet and new PC. Sufficient and modern IT environment to increase your productivity;
- Contract Long term (Trial period 2 months);
- You can learn Japanese language
- 13th month salary and Annual travel.
* Please indicate the position you want to apply

### You’ll be responsible for
* Would you like to work in the lab of software development with Japanese company.
* An international working environment with challenging projects from Japan.
You will work directly with Japanese members.

### Contact
Mr. Long : hr.livepassvn@gmail.com
## Read more: http://www.vietnamworks.com/viec-lam/chi-tiet/ruby-developer-leader-and-senior-638120

**Comment by joneslee85** [comment]
@hoanglongle dear Mr. Long

Thanks for posting job on our board, as you might have known, we care about community, the developers so much that we want to make sure that only good job posts here. And I hope that you take more time to polish up the job post description. Please take time to write a good company profile rather than copying and paste from ITViec post. Furthermore details in *Benefits* and *You'll be responsble for* are not relevant to the headers and thus needs amendment too.

We will close the issue if the description is not amended to meet our standard. Thanks for your understanding.

Kind regards

**Comment by hoanglongle** [comment]
Dear Mr. Joneslee85.
Thanks for reprot for me.
i will edit my post.
Thanks!

**Comment by joneslee85** [comment]
@hoanglongle any update? We will close this job post if no updates made by the end of 2moro
