### ISSUE TITLE
Linkdigital VietNam - Ruby on Rails Developer

### ISSUE THREAD

**Issue by afterclassroom** [awesome-jobs/jobs#158]
## Location

* Da Nang, Vietnam
* Fulltime

## Salary Expectation

* Negotiable

## Requirements
* Ruby
* Rails
* 2+ years Software Engineering experience

### Contact

Dungtqa: dungtqa_at_gmail_dot_com (0905960226)

**Comment by joneslee85** [comment]
Hello thanks for the submission.

Can you please revise this job post? It does not comply with our format. Firstly the title and secondly it has no introduction about your company, the culture, the sort of works or projects. To me, it is not up to the quality par of others. 

I'll close this issue in 2 days if it is not updated with aformentioned feedbacks.
