### ISSUE TITLE
NIC's client - Ruby on Rails - Remote/Hanoi - FT

### ISSUE THREAD

**Issue by huongdx** [awesome-jobs/jobs#160]
## Location

* Hanoi, Vietnam
* Remote

## Salary Expectation

* $600 - $1,000/month

## Requirements
* Ruby
* Ruby developer ( ruby on rails4 )
* MySQL(more than 2 or 3 years)
* HTML5 + CSS3( more than 2 or 3 years if possible)
* JavaScript ( more than 1 year )

## Skills
* English ( read/write )

### Must Have
* Cooperative
* Trustable

### You’ll be responsible for

* Start up new business in Vietnam for Japanese company.

### Contact

Dinh Xuan Huong: huongdx@nicvn.com or skype: huongdinh8668.

**Comment by joneslee85** [comment]
I am sorry to let you know the post does not comply to our [rule](https://github.com/awesome-jobs/jobs/blob/master/README.md):

> ..the company's HR (not recruitment agency), to comply with ..

We only allow the HR team of the company post jobs here.
