### ISSUE TITLE
[ZALORA] - [PHP developers] - [HCMC] - [FT]

### ISSUE THREAD

**Issue by dnguyen61** [awesome-jobs/jobs#172]
**Location**12 Ton Dan, District 4, HCMC, Vietnam

**Salary Expectation:** Above 25m VND

**You should be proficient in:**	
       •	Data structures & algorithms
	•	Object oriented design
	•	Design patterns
	•	Building scalable systems
	•	Any of the following: PHP, Golang, Java, Python, Ruby, iOS, Android, API
	•	Concurrency

**You should have the following qualifications:**
	•	2+ years of experience with high-traffic distributed systems and client-server architectures
	•	BS degree in Computer Science or related technical discipline

**What's in it for you:**
       •	Macs are provided
	•	13th month salary
	•	15 days annual leave 
	•	24/24 Medical insurance coverage for you
	•	Super fun and casual atmosphere
	•	Young and friendly colleagues 
	•	Opportunity to gain working exposure in 8 Southeast Asian markets
	•	You have the ability to make an impact – we’re a startup and your ideas and efforts matter!

**How to apply:**
Simply send your CV to my email (please provide github/stackoverflow account if any). If you have open source work that demonstrates any of the above skills, please do share. 

**Contact**
Dung Nguyen: thuy-dung.nguyen_at_vn_dot_zalora_dot_com (skype: nttd92)

**Comment by joneslee85** [comment]
I am sorry but I have to close this job post for it does not comply with our guideline:

* The title format
