### ISSUE TITLE
[ZALORA] - [5 Frontend Engineers] - [Singapore] - [FT]

### ISSUE THREAD

**Issue by dnguyen61** [awesome-jobs/jobs#175]
At the moment, ZALORA is looking for Frontend Engineers.

**Location:** 182 Clemenceau Avenue #06-00 Singapore 239923
Preferred candidates: Singaporeans, candidates hold WP, PR in Singapore, Malaysian, Phillipinese.. 

As a Frontend Engineer, you will build high performance, scalable and testable components for our shop platform with PHP, JavaScript and other technologies. You will help transition our legacy JS into smart, unobtrusive, well-tested modular JavaScript. You'll also slim down the HTML and CSS to measurably improve browser render and repaint time. We want New Relic's Monday Metrics to make us smile, and we want to keep our customers happy shoppers. You will be working in a diverse, international setting with teammates who are experts in various topics. 

More details on the Frontend Engineer role:
You should be proficient in:
	•	Data structures & algorithms
	•	Design patterns
	•	Javascript frameworks (Angular JS, React)
	•	HTML technologies, e.g., HTML5, DOM processing.
	•	Building scalable systems
	•	Any of the following: PHP, Golang, Java, Python, Ruby, iOS, Android, API
	•	Concurrency
	•	CSS extension languages such as SASS and LESS

You should have the following qualifications:
	•	2+ years of experience with modern frontend development.
	•	2+ years of experience with frontend optimisation for modern e-commerce websites including cross-browser/cross-device optimizations.
	•	BS degree in Computer Science or related technical discipline.

**What’s in it for you?**
	•	Macbook Pro is provided 
	•	Young and friendly colleagues 
	•	Opportunity to gain working exposure in 8 Southeast Asian markets
	•	13th month salary 
	•	100% paid for social & medical insurance 
	•	Join us on our annual company trip every year 
	•	15 days annual leave 
	•	Tons of cool toys (PS4, Foosball etc.) 
	•	Work in one of the most comfy offices around!

How to apply:
Please send your CV and a short cover letter (sharing with us about yourself or your career aspiration) to us. Also, please provide github/stackoverflow account if any. If you have open source work that demonstrates any of the above skills, please do share. 

For further information, please contact us via email at thuy-dung.nguyen@vn.zalora.com (skype: nttd92)

**Comment by joneslee85** [comment]
Thanks for the post.

* I question if this post is really for Vietnamese developers as it seems to target `Singaporeans, candidates hold WP, PR in Singapore, Malaysian, Phillipinese`. (btw s/Phillipinese/Filipino).
* Your title states `Frontend dev` but the body is more like a full stack dev
* Salary is missing
* Title does not comply with our format
* Inconsistent header styling, some are bold and some are not

Overall, it is :-1: from me, to me it is comparable with cheap/spamming job post elsewhere and I would not consider it is worthy to be here unless amendments to be made.

Please be noted, this is not the Job Board like others, it is reserved for elites and best jobs only. I hope you understand and take in my feedbacks constructively.
