### ISSUE TITLE
[ZALORA] - [Senior PHP developers] - [HCMC] - [FT]

### ISSUE THREAD

**Issue by dnguyen61** [awesome-jobs/jobs#177]
ZALORA SEA is looking for Senior Software Engineer roles:

**Salary**: Above 35,000,000VND 
**Responsibilities:**
	•	Improve the stability of the existing codebase.
	•	Improve performance, scalability and reliability of the existing Zalora Shop platform
	•	Build scalable web services
	•	Work aggressively and ship applications that you will be proud of

**Requirements**
	•	BS in Computer Science or related technical discipline or equivalent practical experience
	•	5+ years of experience with high-traffic, high scalable distributed systems and client-server architectures (clustering, partitioning, sharding, etc)
	•	A solid foundation in computer science, with strong competency in data structures, algorithms, software design, and deep understanding of good software design patterns
	•	Passion for building tools to make developers' lives easier
	•	Solid understanding of systems architecture, high scalable system design patterns, how things work underneath each request or UI layer.  
	•	Knowledge of the whole web stack, understand how all the pieces fit together (front-end, web server, load balancer, database, network layer, etc.).

**What’s in it for you?**
	•	Macbook Pro is provided  
	•	Young and friendly colleagues 
	•	Opportunity to gain working exposure in 8 Southeast Asian markets
	•	13th month salary 
	•	Salary review based on performance every 6 months 
	•	100% paid for social & medical insurance 
	•	Join us on our annual company trip, every year 
	•	End-of-year Tet bonus
	•	15 days annual leave 
	•	Tons of cool toys (PS4, Foosball etc.) 
	•	Work in one of the most comfy offices around!

** How to apply:**
Please send your CV to me at : thuy-dung.nguyen@vn.zalora.com 
Also, please provide github/stackoverflow account if any.

**Comment by dnguyen61** [comment]
Hi @joneslee85 . This is my first time posting job here. Could you please let me know how can I add the labels in my job ads posting?

Thanks a lot!

**Comment by joneslee85** [comment]
please edit your job post title as it is not complaint to our spec.

We will add tags once the post is good

**Comment by dnguyen61** [comment]
Thank Trung for the remind. Is it still OK that I put the number for vacancies in the title? Kindly let me know.

Thanks :)

**Comment by dnguyen61** [comment]
Thank Trung for the remind. Is it still OK that I put the number for
vacancies in the title? Kindly let me know.

Thanks :)
<https://github.com/dnguyen61>

On Wed, Mar 30, 2016 at 7:40 PM, Trung Lê <notifications@github.com> wrote:

> please edit your job post title as it is not complaint to our spec.
>
> We will add tags once the post is good
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/awesome-jobs/jobs/issues/177#issuecomment-203413044>
>



-- 

Dung Nguyen | Technical Recruiter

 www.zalora.com      +84 936 101992       nttd92

ZALORA is *always hiring engineers! <http://jobs.engineering.zalora.com/>*

<https://www.linkedin.com/company/zalora-sea>

**Comment by joneslee85** [comment]
No, it is not. Please remove the salary line and the square brackets.
