### ISSUE TITLE
[ZALORA] - [Data Engineers] - [HCMC] - [FT]

### ISSUE THREAD

**Issue by dnguyen61** [awesome-jobs/jobs#179]
At the moment, ZALORA SEA is looking for Data Engineer to join our data science team at ZALORA. As a Data Engineer, your work will mainly involve in the process of collecting, storing, processing, and analyzing data generated from our database. You will be working in a diverse, international setting with teammates who are experts in various topics. We often conduct workshops to improve our individual skill sets, and to improve our workflow as a team.

**Salary:** Above 25,000,000 VND

**You should be familiar with: **
• Data structures & algorithms 
• Any of the following languages: R, Python,PHP, Golang, and Java, Hadoop (or Spark) framework 
• Any of the following databases: MySQL, NoSQL, MongoDB, HBase, Cassandra You should have knowledge in: 
• Object oriented design and design patterns 
• Large-scale distributed system systems 
• Concurrency systems 

You should have the following qualifications: 
• BS degree in Computer Science or related technical discipline 
• Fresh graduates are welcome to apply Optional: having the following skills is a plus 
• Good background in statistics 
• Knowledge in data analysis, data mining, or machine learning
• Experience in working with big data 

**What's in it for you?**
- Laptop is provided
- Young and friendly colleagues
- Opportunity to gain working exposure in 8 Southeast Asian markets
- 13th month salary
- 100% paid for social & medical insurance
- Join us on our annual company trip every year
- 15 days annual leave
- Tons of cool toys (PS4, Foosball etc.)
- Work in one of the most comfy offices around!

**How to apply:** Please send your CV and a short cover letter (sharing with us about yourself or your career aspiration). If you have open source work that demonstrates any of the above skills, please do share.

Contact: Dung (Jan): thuy-dung.nguyen@vn.zalora.com

**Comment by joneslee85** [comment]
please remove square brackets from title

**Comment by joneslee85** [comment]
also fix the header format for You should be familiar with
