### ISSUE TITLE
[Web developer - Senior Ruby on Rails] 

### ISSUE THREAD

**Issue by KimNguyenMai** [awesome-jobs/jobs#184]
## Location

* Firstly, working online from Vietnam.
* After 6-9 months relocate to America with the whole company. 

## Salary Expectation

* around 1000 euro/month, negotiable

## Requirements
* Ruby
* Senior Ruby on Rails 
* Fluent in English 
*Can start working immediately without training period
* Software Engineering experience

### Must Have

* Be able to relocate to San Francisco with the company
* Be able to work well and confident in Ruby on Rails 

### Ideally

* Experience with Ruby on Rails 

### Responsibilities

Main web developer of the company

### You’ll be responsible for

* Develop and build parts of a new Company website 

### You can bring

* A good eyes for design
* A good analysis skill

### Contact

First line recruitment: Ms. Kim Nguyen: maikim200295@gmail.com (If you have, please attach some of your previous projects for us to have a fair judgment)

**Comment by joneslee85** [comment]
Dear Ms Kim, I am sorry but your post is not qualified for:

* Post format does not comply with our guideline, the title
* Post content is super poor, pretty much like a spam post
* No details on the company, so it seems to me your are a recruiter and we do not allow third-party recruiter posting here

If you believe this is not the case, please feel free to make amendment and re-open the post for another round of review.
