### ISSUE TITLE
8 Bit Rockstars - 03 Senior PHP Developers - Saigon - FT

### ISSUE THREAD

**Issue by 8BIT-ROCKSTARS** [awesome-jobs/jobs#196]
![8BR](http://8bitrockr.com/img/logo_w.png)
# 8 BIT ROCKSTARS
Floor 8th, Vincom B, 72 Le Thanh Ton, Ben Nghe Ward, Dist.1, HCMC
http://8bitrockr.com/
hr@8bitrockr.com

#### Salary: VERY ATTRACTIVE
Email CV to: **_hr@8bitrockr.com_**

## About us

• **8 Bit Rockstars** is part of the global NFQ enterprise that began in 2000 in Germany and spans Europe, Vietnam, and Singapore.
• We empower successful international startups, large websites and highly scaled applications worldwide.
• We have 15 years of experience in building high-performing teams out of Europe. Currently over 250 NFQ engineers accelerate the success of various high profile startups worldwide including leading US websites like KAYAK.com.
• 8 Bit Rockstars is the nation's coolest agile tech firm, specializing in PHP, and one of the leaders in utilizing Elasticsearch.

## Job Description

We are looking for people who can work well independently and love to be part of a team. 

• **Rockstar** - Join our Rockstars team to truly become Front End Rockstar
• **Fun** - Join a young and dynamic team in an international, professional and English speaking working environment
• **Tech Rockstar** - Apply the latest technology like ReactJs, AngularJs, ES6/7 etc...
• **Exciting Projects** - Working with oversea clients and awesome projects 
• **Experience** - Use your experience to building great Web-Apps
• **Problem Solver** - Ability to find answers through researching and reading documentation

**Who will you work with?**

• You will be working with international clients on very interesting products. This is not the standard corporate website job but high load, complex projects which require dedication, skill and that you put your heart into the job. This is an excellent opportunity to gain experience, deliver happiness, and push your technical boundaries.
• In this role you will work directly with international clients to scale and maintain one of their sites using technology such as: Symfony2, Elasticsearch, Laravel, Drupal, Memcached, RabbitMQ, AngularJS, React, React native and much more. If you are experienced in any of these technologies or have knowledge in something similar please mention that in your cover letter.

 
**What will you do?**

- Lead a highly skilled team that works long term on exciting projects -- No short term projects, we deliver quality
- Be an expert and suggest new technologies to our clients and the team
- Define architecture solutions and framework for projects
- Design high level solutions and approaches for new projects
- Build up core components and strengthen core technology capacity
- Research and apply cutting-edge technologies and develop new ways of unlocking knowledge
- Be a part of the open source community

### Skill and experience:

- Very good English communication skills
- Experience developing web applications
- 3+ years PHP
- 2+ years in any of the above mentioned technologies
- Database Experience - SQL / RDBS, Memcached
- Test driven development
- PHPUnit/PHPSpec/Codeception 
- Strong understanding of OOP/OOD 
- GIT

### Big Plus

- Agile Development / SCRUM 
- Big Data, NoSQL, Redis 
- Design Patterns 
- jQuery / AngularJS / React / React native 
- Elasticsearch

### What We Can Offer

• Oportunity to grow and learn from other talented individuals. 
• Opportunities to work with International Experts and cool startup entrepreneurs
• Work as a member in fun, fast-paced, and friendly team
• Very fun and friendly colleagues, global and professional working environment
• Modern office in District 1 with entertainment zone, relax area, coffee bar, etc.

8 Bit Rockstars has been featured in Tech in Asia and e27. 

### Benefits include:
• Open and honest culture where people are valued, treated fairly, trusted and empowered to do great things
• Attractive, **competitive salary** and incentives
• Year end **bonus** (13th month salary ++)
• 40 hour work weeks (9:00-18:00, Mon-Fri)
• **15 days** of vacation per year
• **Probation** with **100% of salary**
• Performance and **salary review** every **6 months**
• **International Medical Insurance** will be paid by the company
• **English Class** with foreigner 3 times a week.
• New **Technologies Club** every week
• Quarterly **rockstar Hackathon** with the Best prizes
• Short and long-term **international training** / work
• **Company trip** (local or internationally) every year
• **Team building events**, party monthly and much more
• **Entertainment Zone** for all members with full media in company (game, music, TV…).
• Enjoy **Relax and Coffee Bar** in company.

Email CV to: **_hr@8bitrockr.com_**

**Comment by tucq88** [comment]
Are you open for an `remote position` ?

**Comment by 8BIT-ROCKSTARS** [comment]
Hi @tucq88 ,

It is very unfortunate to say that, at the moment, we are only looking for full time and fixed-term contract candidates, working at our office at Vincom Center HCMC.

Regards,

**Comment by joneslee85** [comment]
it's good to know you have foubd the right person. congrats
