### ISSUE TITLE
Tuyển lập trình PHP 600$ - 1000$

### ISSUE THREAD

**Issue by hangpham308** [awesome-jobs/jobs#206]
VNEXT SOFTWARE CẦN TUYỂN LẬP TRÌNH VIÊN PHP - 600$ - 1000$

YÊU CẦU:
- Có kinh nghiệm lập trình PHP từ 2 năm trở lên
- Có kinh nghiệm HTML, CSS và MySQL 
- Đã có kinh nghiệm làm việc với một trong các framework: Zend, cake, lavarel.....
- Từng làm việc với hệ thống có số lượng Record lớn
- Nhiệt tình, chăm chỉ, vui vẻ, hòa đồng.

CHẾ ĐỘ:
- Nghỉ thứ 7 và Chủ Nhật
- ĐIỀU CHỈNH LƯƠNG 2 lần/năm 
- TEAMBUILDING 4 lần/ năm
- KHÁM SỨC KHỎE hàng năm theo nhu cầu cá nhân
- THƯỞNG DỰ ÁN/NGÀY LỄ
- GIẢI TRÍ: Game AOE, Pi -a, phượt, ăn uống đình đám mỗi tháng một lần, đặc biệt là đội bóng đá hoạt động sôi nổi.
- QUỸ ĐÀO TẠO KHÔNG GIỚI HẠN, các lớp học tiếng Nhật và tiếng Anh được tổ chức
- THƯỞNG CHỨNG CHỈ (Bằng cấp/chứng chỉ bạn vẫn giữ)
- Cơ hội đi Nhật ngắn hàn và dài hạn
- Làm việc theo mô hình Agile, Scrum

Chi tiết vui lòng liên hệ: 
- Email: hr@vnext.vn
- Skype: hangpham308
- Tel: (84 4)3765-9555/3765-9333
---------------------------------------
56 Lưu Hữu Phước, Cầu Diễn, Nam Từ Liêm, Hà Nội
http://facebook.com/tuyendungvnextsoftware
http://vnext.vn/vn

**Comment by hieuk09** [comment]
I am sorry but your post is not qualified for:

- Post format does not comply with our guideline
- Post content is super poor, pretty much like a spam post
- No details on the company, so it seems to me your are a recruiter and we do not allow third-party recruiter posting here

If you believe this is not the case, please feel free to make amendment and re-open the post for another round of review.
