### ISSUE TITLE
job.md

### ISSUE THREAD

**Issue by jankolario** [awesome-jobs/jobs#207]
# Python Developer/ka na vytisknutí ± 30 000 triček

Hledáme full-time / part-time Python vyvojáře:
![](http://i.giphy.com/u2UWxUJ9AAoKY.gif)

TLDR
Kde: Praha
Kdy: Červen - Prosinec
Na čem: Jack.cz/Jack.sk.
Plat: 50 000 - 80 000 CZK

## Máme nachystáno:

* Široký záběr práce, naučíe se:
   *  s back-endem napojený na desítky tiskařských strojů Brother GT-3, který zvládne vytisknout stovky triček denně.​
*  spravovat automatizovaně desítky tisíc reklam
* o fungování námi napsaného ecommerce projektu pro Česko, Slovensko, Polsko a Německo
* Zkušený tým (není to první projekt: Techsquat, Bitbrno, Bileto)​
  * [Pavel Král](http://github.com/pavelkraleu)
  * [Vladimír Mokrý](http://vmokry.com)
  * Jan Antonín Kolář – linkedin.com/in/janantoninkolar

## požaduje

[link to Google!](http://google.com)

- George Washington
- John Adams
- Thomas Jefferson
👍
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* $????/month or negotiable

## Requirements
* Ruby
* Lotus Framework
* PostgreSQL
* 5+ years Software Engineering experience

### Must Have

* Be able to fly
* Be able to dodge bullet

### Ideally

* Experience with 

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Building a new Facebook

### You can bring

* A good eyes for design
* A good analyis skill

Jack je:
* ⅓ back-end napojený na desítky tiskařských strojů Brother GT-3, který zvládne vytisknout stovky triček denně.​
*⅓ marketingová agentura, která spravuje tisíce reklam.
* ⅓ Z jedné třetiny ecommerce řešení pro Česko, Slovensko, Polsko, Německo a Rakousko. 

http://www.tyinternety.cz/ostatni/salinou-za-bitcoiny-brno-jako-prvni-mesto-vyzkouselo-jestli-to-jde/
http://www.lupa.cz/clanky/reportaz-brnensky-techsquat-je-klaster-pro-podnikave-geeky/
http://www.tyinternety.cz/startupy/startuje-bileto-dalsi-projekt-s-jakubem-havrlantem-v-pozadi/

### Contact
jan@jack.cz
+420.775272827
Trollman: trollman_at_gmail_dot_com (mobile number optional)

It will be :boom:

**Comment by huydx** [comment]
@joneslee85 it seems that this issue is a troll, closed it.

**Comment by jankolario** [comment]
@huydx I am sorry, it was mistakenly posted it. Is it possible to delete it?

**Comment by huydx** [comment]
@jankolario i closed it so it is fined
