### ISSUE TITLE
Ave88 - Junior Elixir developer - HCMC/Remote - FT

### ISSUE THREAD

**Issue by lessless** [awesome-jobs/jobs#212]
## Location

* Saigon, Vietnam (at least 3 days a week  during probation period)
* Remote (after probation period) 

## Salary Expectation

* Competitive

## Requirements (Absolutely necessary)
- Higher education in Computer Science
- Ability to act both independently and as a team player
- Attention to details
- Responsibility  and accountability
- Ability to think logically and rationally
- Desire for professional growth and development 
- Interest in functional programming

## Skills
- Basic Elixir skills (bare bones minimum is https://elixirschool.com +  practical experience even on the educational projects) 
- Familiarity with OOD  principles ( at least SID from SOLID) 
- Database theory  understanding
- At least 6 months of real-world programming experience (after the University) 
- Upper-intermediate/B2 English level
- BDD (we test **everything**)
- Web applications development experience with Phoenix/Ruby on Rails/Laravel/etc.

### Additional points for
- Category theory understanding
- Familarity  with Ruby language
- Interest in cryptocurrencies
- Familiarity with document-oriented databases 

### Responsibilities

Write clean code, enjoy your life, work in remote team 

### You’ll be responsible for

Porting our existing application from RoR to Elixir/Phoenix stack, including frontend, which might end up in React/Redux or ELM app.

### You can bring

* Critical thinking
* Big dreams
* Humble personality 

### Contact

Send your CV and salary expectations to yevhenii.kurtov@gmail.com

**Comment by huydx** [comment]
nice to have first elixir job!

**Comment by tieubao** [comment]
@lessless I have just bought Phoenix Programming book! 😉

**Comment by lessless** [comment]
@tieubao greetz! it's a really long journey. I wish I learned FP since high school.

**Comment by giangstrider** [comment]
nice @lessless

**Comment by joneslee85** [comment]
it is probably the very first in Vietnam

**Comment by kiennt** [comment]
nice @lessless

**Comment by lenguyenthanh** [comment]
@lessless I have experience with FP but never work on real project as well as Elixir but I'm confident that I qualify others requirements. Do I have a chance here?

Could you please review my github profile to know more about me?

Thanks!

**Comment by lessless** [comment]
Hi, @lenguyenthanh. I'm rather looking for a like-minded newbie than for an established developer, some technologies are new for me as well and everybody will learn during  along the way.
Can you please contact me directly on email yevhenii.kurtov@gmail.com and tell more about yourself, your experience and point to any particular repositories that you are willing to share?

**Comment by lenguyenthanh** [comment]
Hi Thank you @lessless, will contact you this afternoon.

**Comment by lessless** [comment]
We are super happy to have @lenguyenthanh as our first Vietnamese team member!  :godmode:

thank you @kiennt, we hope to have something to share during the next elixir meetup :)

**Comment by lessless** [comment]
Thanks everyone for the interest and your letters! The issue can be close as we found our perfect candidate  :godmode:

thank you @kiennt, we hope to have something to share during the next elixir meetup :) 

thank you @kiennt, we hope to have something to share during the next elixir meetup :)

**Comment by lessless** [comment]
Thanks everyone for the interest and your letters! The issue can be close as we found our perfect candidate  :godmode:

thank you @kiennt, we hope to have something to share during the next elixir meetup :)

**Comment by joneslee85** [comment]
@lessless it is my pleasure to see that the board truly works for your company. I hope you help spread the words about us.

**Comment by lessless** [comment]
@joneslee85 always!
