### ISSUE TITLE
Golden Owl's client - Senior RoR developer - HCMC - FT

### ISSUE THREAD

**Issue by Rosedao03** [awesome-jobs/jobs#213]
## Location

* Saigon, Vietnam

## Salary Expectation

* USD 1000+ /month or negotiable

## Requirements
* Ruby
* Lotus Framework
* PostgreSQL
* 4+ years Software Engineering experience

## Skills
* Good English communication to work with Singapore clients

### Responsibilities

Great power comes with great responsibilities!

### You can bring

* A good eyes for design
* A good analyis skill

### Contact

Rose: rose.dao712@gmail.com (or phone number: 0932353950)

**Comment by joneslee85** [comment]
Thanks for posting with us. I am sorry that we have to reject this post on the ground that this post does not comply with our guideline, that is _posted by the HR of the company_. It seems to me your are an agent that represent Golden Owl. Feel free to provide us more proof if you are working for Golden Owl and we could re-open the job post for you.
