### ISSUE TITLE
Blockchain Technology R&D -- We want YOU!!!

### ISSUE THREAD

**Issue by ThanhCardano** [awesome-jobs/jobs#214]
System Developers (java/nodejs/python/golang)
Company: Cardano Labo VietnamLevel 2, Athena Building, 146 - 148 Cong Hoa, Tan Binh District, HCMC
Work Location: Ho Chi Minh

What We Can Offer
Thưởng Lương Tháng 13 + Bonus dự án
Khám sức khỏe định kì hằng năm
Du lịch công ty hàng năm, cơ hội công tác Nhật Bản

You Should Be Best At
Sql/nosql  Back-end, Network, Blockchain, Bitcoin  Java/nodejs/python/golang 

What You Will Do
- Lập trình Business system (hệ thống nghiệp vụ) theo yêu cầu.
- Kiểm tra (Test) và sửa lỗi của sản phẩm.
- Nghiên cứu các công nghệ mới để giải quyết những vấn đề kỹ thuật.

What You Are Good At
- Có ít nhất 2 năm kinh nghiệm một trong những ngôn ngữ Java/ Javascript/ NodeJS/ Python/ GoLang/ PHP/ C++/ C#/ ASP .NET/ Android/ iOS.
- Có kiến thức sâu về cấu trúc dữ liệu và giải thuật.
- Có kiến thức về SQL (Oracle, MySQL, Postgre) hoặc NoSQL (LevelDB, MongoDB, CouchDB), Big Data (Hadoop)
- Có kiến thức về PhoneGap, Titanium, Cocos, Unity, Qt for Mobile
- Ưu tiên: Back-end, Network, Server, Socket, Blockchain, Bitcoin, Ethereum, Crypto Currency.
- Có khả năng đọc, viết tài liệu bằng tiếng Anh hoặc tiếng Nhật.

About Our Company
Cardano Labo VietnamLevel 2, Athena Building, 146 - 148 Cong Hoa, Tan Binh District, HCMC
Cardano Labo Vietnam là công ty lập trình hệ thống chuyên về lĩnh vực tiền tệ điện tử "cryptocurrency" (sử dụng mã hóa để bảo mật), có chi nhánh ở Tokyo, HongKong, Campuchia. Chúng tôi đang hướng tới mục tiêu phát triển các dịch vụ sử dụng công nghệ tiên tiến trên thế giới như "Smart contract" (hợp đồng thông minh), "Block chain" (hệ thống ngân hàng tiền tệ kỹ thuật số). Ở Mỹ, đây là công nghệ mã hóa được giảng dạy tại các trường đại học danh tiếng như MIT, Stanford và đang được các doanh nghiệp lớn tin tưởng, sử dụng lâu dài. Gần đây, một số doanh nghiệp lớn của Nhật cũng bắt đầu sử dụng công nghệ này tại châu Á. Tuy nhiên, công nghệ này vẫn chưa được sử dụng trong lập trình ở châu Á, trong đó có Việt Nam. Tham gia vào lĩnh vực này, tức là chúng ta đang đi tắt, đón đầu công nghệ. Nhiệm vụ của chúng tôi là làm cho thế giới trở nên phong phú và tiện nghi hơn bằng cách phổ biến và mở rộng thị trường cho các dịch vụ sử dụng công nghệ mã hóa, trong đó tiêu biểu là Bitcoin - một loại tiền tệ kỹ thuật số có khả năng tạo nên cuộc cách mạng trong lĩnh vực kinh doanh trên thế giới. Cardano Labo Vietnam đang thành lập dự án phát triển game, dịch vụ dựa vào công nghệ mã hóa tối tân và hiện đang tìm kiếm các nhân tài phù hợp cho dự án.

**Comment by huydx** [comment]
@ThanhCardano can you please comply with job guideline at https://github.com/awesome-jobs/jobs, or we have to close your job description :)

**Comment by lessless** [comment]
Cryptocurrencies, yay!! 
Go for it Vietnam!!! :sparkling_heart::sparkling_heart::sparkling_heart:

**Comment by joneslee85** [comment]
It has been 2 days without any amendment. I don't believe that you don't care enough. I am sorry that I have to close off this job as it looks to me as a spam.
