### ISSUE TITLE
Ring.MD -  Senior Ruby on Rails developer - Singapore - FT

### ISSUE THREAD

**Issue by longkt90** [awesome-jobs/jobs#59]
RingMD is a young startup with a small team of less than 10 people and we inspire each other to innovate and provide the best service in Healthcare. We are currently seeking candidates to join our team full time as a Web developer. 

# Job Description:
- Join Ruby on Rails developers team to build web app and APIs for our product, Ring.MD
- Work in RingMD Singapore office (Employment Pass sponsor).
- Do research on technology that can benefit the app.
- Code review and design discussion with teammates.

# What we’re looking for

1/ Are you bright, not just smart?

We’re looking for generalists. That doesn’t mean that you already know everything; it means that you’re both willing and able to learn new things quickly. We’re looking for conceptual thinkers. Can you think about problems at a high level and then solve them in code with a constant focus on the higher-level problem you’re solving?

2/ Do you fit?

Culture is critically important here. Not only do we need people who can work well in small teams, we also want to make sure that our values mesh. We believe in collaboration across the entire company, taking responsibility to make things work, and delivering a product which delights our users.

## Must have:
 - 2+ years experience writing web applications using Ruby, RoR
 - Experience with MySQL/PostgreSQL
 - Be able to communicate and or at least to write in English
 - Solid understand about TCP/IP, RESTful, test automation
 - Experience in JavaScript, AngularJs, jQuery, and frontend dev
 - Git experience

## Ideally
 - Experience architecting large scale Ruby/Rails applications
 - Knowledge/experience with redis, memcached
 - Experience building responsive web applications
 - An active participation of open source projects

# Why work at RingMD?

By joining the team as a developer, you’ll be an intricate part of working on product that will have massive impact on millions of users. Your voice will be heard and you’ll have a lot of autonomy over mission-critical decisions. We make healthcare more convenient and affordable.

##  Benefit:
- High and competitive salary
- Young and proactive working environment
- You have more control and flexibility

# Contact us
- Please send your CV to long(at)ring.md

**Comment by handleror** [comment]
:+1:

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md

**Comment by joneslee85** [comment]
@longkt90 =_= no salary in the title please

**Comment by longkt90** [comment]
Lol OK, I just take a look at opening issues and see many of them have salaries. I thought I miss something :))
